const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');const {eligible,validate,compare}=require('./promote-approved.cjs');
const bytes=Buffer.from('version: 0.5.1-beta.2\nfiles:\n  - url: RaceIO-0.5.1-beta.2.zip\n    sha512: abc\n    size: 10\npath: RaceIO-0.5.1-beta.2.zip\nsha512: abc\n');
const release=()=>({version:'0.5.1-beta.2',status:'released',approved:true,build:{verified:true,macFeed:{signed:true,sha256:crypto.createHash('sha256').update(bytes).digest('hex'),url:'https://github.com/willbamber/raceio-desktop-updates/releases/download/beta-feed/RaceIO-0.5.1-beta.2-beta-mac.yml'}}});
test('testing, unchecked approval, unsigned and foreign feeds cannot promote',()=>{for(const edit of [r=>r.status='testing',r=>r.approved=false,r=>r.build.macFeed.signed=false,r=>r.build.macFeed.url='https://evil.invalid/manifest']){const r=release();edit(r);assert.equal(eligible(r,'mac'),false);assert.throws(()=>validate(bytes,r,'mac'));}});
test('approved manifests must match their trusted digest',()=>{assert.equal(validate(bytes,release(),'mac').version,'0.5.1-beta.2');assert.throws(()=>validate(Buffer.from('tampered'),release(),'mac'),/digest/);});
test('version ordering prevents downgrade and handles numeric beta numbers',()=>{assert.ok(compare('0.5.1-beta.10','0.5.1-beta.2')>0);assert.ok(compare('0.5.0-rc.9','0.5.1-beta.2')<0);assert.throws(()=>compare('bad','0.5.1-beta.2'));});
test('approved handoff checks installer bytes and approval again before publishing',async()=>{
 const {main}=require('./promote-approved.cjs'),fs=require('node:fs');const pkg=Buffer.from('signed installer fixture'),sha512=crypto.createHash('sha512').update(pkg).digest('base64');const manifest=Buffer.from(`version: 0.5.1-beta.2\nfiles:\n  - url: RaceIO-0.5.1-beta.2.zip\n    sha512: ${sha512}\n    size: ${pkg.length}\npath: RaceIO-0.5.1-beta.2.zip\nsha512: ${sha512}\n`);const r=release();r.build.macFeed.sha256=crypto.createHash('sha256').update(manifest).digest('hex');let approvals=0,published=0;const request=async url=>{if(url.includes('/functions/')){approvals++;return new Response(JSON.stringify([r]));}if(url.endsWith('/beta-mac.yml'))return new Response('version: 0.5.1-beta.1\n');if(url.endsWith('.zip'))return new Response(pkg);return new Response(manifest);};await main({request,publish:target=>{assert.deepEqual(fs.readFileSync(target),manifest);published++;}});assert.equal(published,1);assert.equal(approvals,2);
 r.status='testing';published=0;await main({request,publish:()=>published++});assert.equal(published,0);
 r.status='released';await assert.rejects(main({request:async url=>url.endsWith('.zip')?new Response('broken'):request(url),publish:()=>published++}),/integrity/);assert.equal(published,0);
});
